name: plugins
description: A new Flutter project_views.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons fonts to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  dio: ^4.0.0
  # 主题管理：https://pub.dev/packages/adaptive_theme
  adaptive_theme: ^2.2.0
  # 自定义导航/路由处理：https://pub.dartlang.org/packages/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.1.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.0.2
  # 状态管理 https://pub.dev/packages/provider
  provider: ^6.0.0
  # 不同屏幕尺寸的适配 https://pub.dev/packages/responsive_builder
  responsive_builder: ^0.4.1
  # 轻量且强大的解决方案：高性能的状态管理、智能的依赖注入和便捷的路由管理 https://pub.dev/packages/get
  get: ^4.3.8
  # https://pub.dev/packages/webview_flutter
  webview_flutter: ^2.0.12
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.9
  # loading  https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.3
  # https://pub.dev/packages/animated_text_kit/versions
  animated_text_kit: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons fonts is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # assets-generator-begin
  # assets/images/*
    - assets/images/icon_none.png
    - assets/images/icon_others.png
    - assets/images/icon_search.png
    - assets/images/icon_back_black.png
    - assets/images/icon_setting.png
    - assets/images/icon_custom.png
    - assets/images/icon_expand.png
    - assets/images/icon_ellipsis.png
    - assets/images/icon_delete.png
  # assets-generator-end

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the fonts family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the fonts. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Canterbury
      fonts:
        - asset: assets/fonts/Canterbury.ttf

    - family: HelloStockholm
      fonts:
        - asset: assets/fonts/HelloStockholm.otf

    - family: Horizon
      fonts:
        - asset: assets/fonts/Horizon.otf

    - family: Bobbers
      fonts:
        - asset: assets/fonts/Bobbers.ttf

    - family: Agne
      fonts:
        - asset: assets/fonts/Agne.otf
